# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default_twitter: &default_twitter
  twitter_api_key: 	'KnTe2iL0YwBdXboJTnIPz8K4k'
  twitter_api_secret: '7oq0JDC9AK5EPldKoANmrErPZ3WQdHOwArfFASqLCgcIgUmRvX'

development:
  secret_key_base: 1fa34cf75504f6d846979099ca94966b4652d15b91be797f47977f5e203c76cec6d62eb867430997dcd1ab8081271f13b55e3059aba7d4729d623bb34a4fb07c
  <<: *default_twitter

test:
  secret_key_base: ef35ea146b8a9110b58425a0d75a2a769d0f3c9d80e7a04cb02d1ee0ede14476f948f48a5f6e98e12163bfc5c9b8045084b0733d4540f32fd4a1db320ea280c0
  <<: *default_twitter

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
